#!/usr/bin/env bash
user=$(whoami)
uid=$(id -u "$user")

service_name='com.kanata.starter'
service_target="gui/$uid/$service_name"
service_plist="$HOME/Library/LaunchAgents/$service_name.plist"
stderr_log="/var/log/$service_name.err.log"
stdout_log="/val/log/$service_name.out.log"
kanata_sudoers='/etc/sudoers.d/kanata'
kanata_starter='/usr/local/bin/kanata_starter.sh'

check_installed() {
    if [[ -f "$service_plist" && -f "$kanata_sudoers" ]]; then 
        echo "Kanata starter already installed!"
        return 0
    fi
    echo "Service isn't installed."
    return 1
}
check_bootstrapped() {
    if launchctl print "$service_target" &> /dev/null; then
        return 0  # (bootstrapped)
    else
        return 1  # (not bootstrapped)
    fi
}

clear_logs() { 
    [[ -f $stderr_log ]] && truncate -s 0 $stderr_log
}

add_kanata_sudoer() { 
    # add kanata file in sudoers.d
    echo "$user ALL=(root) NOPASSWD: sha256:$(shasum -a 256 "$kanata_binary") --cfg $kanata_config --quiet" 1> ./kanata.tmp
    sudo chown root:wheel ./kanata.tmp
    sudo chmod 600 ./kanata.tmp
    sudo cp -vp ./kanata.tmp $kanata_sudoers && rm -rf ./kanata.tmp
}

generate_kanata_binary() {
    sed_script="s~{kanata_binary}~$kanata_binary~g; s~{kanata_config}~$kanata_config~g"

    if sed -e "$sed_script" ./kanata_starter.sh > ./kanata_starter.sh.tmp; then
        echo "Binary file created!"
        return 0
    else
        echo "ERROR creating the binary file, make sure kanata_starter exists"
        return 1
    fi
}

generate_service_file() {
    sed_script="s~{stderr_log}~$stderr_log~g; s~{stdout_log}~$stdout_log~g; s~{kanata_starter}~$kanata_starter~g"

    if sed -e "$sed_script" ./"$service_name.plist" > ./"$service_name.plist.tmp"; then
        echo "Service file created!"
        return 0
    else
        echo "ERROR creating the service file, make sure $service_name.plist exists"
        return 1
    fi
}

install() { 
    if ! check_installed; then
        add_kanata_sudoer
        if generate_kanata_binary; then
            sudo chmod 644 ./kanata_starter.sh.tmp
            sudo chmod +x ./kanata_starter.sh.tmp
            sudo cp -vp ./kanata_starter.sh.tmp $kanata_starter && rm -f ./kanata_starter.sh.tmp
            printf "\n"
        fi
        if generate_service_file; then
            sudo chmod 644 ./$service_name.plist.tmp
            sudo cp -vp ./$service_name.plist.tmp "$service_plist" && rm -f ./$service_name.plist.tmp
            printf "\n"
        fi
        echo "Installed service."
    fi
}


function start { 
    if check_installed; then
        clear_logs
        if check_bootstrapped; then
            launchctl kickstart "$service_target"
        else
            launchctl enable "$service_target"
            launchctl bootstrap gui/"$uid" "$service_plist" && echo "Kanata service starting..."
            sleep 2
            echo "Started."
        fi
    fi
}

stop() { 
    if check_installed; then
        if check_bootstrapped; then
            echo "Suspending the server..."
            launchctl bootout gui/"$uid" "$service_plist"
            read -r -d "," -s -t 2 --
            launchctl disable "$service_target"
            echo "Suspended."
        else
            launchctl kill 9 "$service_target" &> /dev/null
        fi
  fi
}

restart() { 
  if check_installed; then
    if check_bootstrapped; then
      clear_logs
      launchctl kickstart -k gui/"$uid"/$service_name && echo "Service restarting..."
    else
      stop
      start
    fi
  fi
}

debug() { 
    if check_installed; then
        tail -n 50 -f $stderr_log
    else
        echo "Service isn't installed."
    fi
}

info() { 
    if check_installed; then
        if check_bootstrapped; then
            launchctl print "$service_target"
        else
            echo "Service not running."
        fi
    fi
}

uninstall() { 
    # if check_installed; then
    stop
    echo "Deleting..."
    sudo rm -vf "$service_plist"
    sudo rm -vf "$kanata_sudoers"
    sudo rm -vf "$kanata_starter"
    clear_logs
    printf "\n"
    echo "Uninstalled service"
  # fi
}

help() { 
  echo "Usage:
    Installation: kanata-service install <kanata_binary> <kanata_config>
    Other: kanata-service <command>

Available commands:
    1. install - installs the launchd com.kanata.plist file & and adds kanata to sudoers.d
    2. uninstall - deletes the launchd com.kanata.plist file & removes the kanata sudoers.d
    3. start - starts the service
    4. stop - stops the service
    5. restart - restarts the service
    6. info - prints properties of the com.kanata launchd service
    7. debug - concatenates the stderr.log to stdout"
}

invalid_syntax() {
  echo 'Invalid syntax'
  printf '\n'
  help
}

main() {
    case $# in
        0)
            help
            ;;
        1)
            [[ "$1" != "install" ]] && $1 || invalid_syntax
            ;;
        3)
            if [[ "$1" == "install" ]]; then
                kanata_binary=$2
                kanata_config=$(realpath "$3")
                "$1"
            else
                invalid_syntax
            fi
            ;;
        *)
            invalid_syntax
            ;;
    esac
}

main "$@"
